CREATE TABLE lesson_item (id INTEGER AUTO_INCREMENT NOT NULL, event_date DATE, description VARCHAR(255), start_time INTEGER, stop_time INTEGER, title VARCHAR(255), lesson_id INTEGER, PRIMARY KEY (id))
CREATE TABLE calendar_entry (id INTEGER AUTO_INCREMENT NOT NULL, calendar_type VARCHAR(31), start_time INTEGER, stop_time INTEGER, date_exp VARCHAR(255), repeat_start_date DATE, repeat_stop_date DATE, oneoff_date DATE, PRIMARY KEY (id))
CREATE TABLE tutor (id INTEGER AUTO_INCREMENT NOT NULL, display_name VARCHAR(255), email VARCHAR(255), name VARCHAR(255), password VARCHAR(255), time_zone VARCHAR(50), ts_fri VARCHAR(255), ts_mon VARCHAR(255), ts_sat VARCHAR(255), ts_sun VARCHAR(255), ts_thu VARCHAR(255), ts_tue VARCHAR(255), ts_wed VARCHAR(255), PRIMARY KEY (id))
CREATE TABLE lesson (id INTEGER AUTO_INCREMENT NOT NULL, capacity INTEGER, description VARCHAR(255), status VARCHAR(255), title VARCHAR(255), calendar INTEGER, client_id INTEGER, tutor_id INTEGER, PRIMARY KEY (id))
CREATE TABLE calendar_snapshot (id INTEGER AUTO_INCREMENT NOT NULL, client_comment VARCHAR(255), event_date DATE, start_time INTEGER, stop_time INTEGER, tutor_comment VARCHAR(255), client_id INTEGER, tutor_id INTEGER, PRIMARY KEY (id))
CREATE TABLE client (id INTEGER AUTO_INCREMENT NOT NULL, display_name VARCHAR(255), email VARCHAR(255), name VARCHAR(255), password VARCHAR(255), time_zone VARCHAR(50), PRIMARY KEY (id))
ALTER TABLE lesson_item ADD CONSTRAINT FK_lesson_item_lesson_id FOREIGN KEY (lesson_id) REFERENCES lesson (id)
ALTER TABLE lesson ADD CONSTRAINT FK_lesson_client_id FOREIGN KEY (client_id) REFERENCES client (id)
ALTER TABLE lesson ADD CONSTRAINT FK_lesson_tutor_id FOREIGN KEY (tutor_id) REFERENCES tutor (id)
ALTER TABLE lesson ADD CONSTRAINT FK_lesson_calendar FOREIGN KEY (calendar) REFERENCES calendar_entry (id)
ALTER TABLE calendar_snapshot ADD CONSTRAINT FK_calendar_snapshot_client_id FOREIGN KEY (client_id) REFERENCES client (id)
ALTER TABLE calendar_snapshot ADD CONSTRAINT FK_calendar_snapshot_tutor_id FOREIGN KEY (tutor_id) REFERENCES tutor (id)
